# Generated by Django 5.0 on 2024-01-03 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='order_date',
        ),
    ]
