# Generated by Django 5.0 on 2024-01-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_color',
            field=models.CharField(choices=[('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue')], default='Red', max_length=5),
            preserve_default=False,
        ),
    ]
