# Generated by Django 5.0 on 2024-01-03 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_option_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='votes',
            new_name='selections',
        ),
    ]
