# Generated by Django 5.0 on 2024-01-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_product_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('order_date', models.DateTimeField(verbose_name='date ordered')),
                ('products', models.ManyToManyField(to='shop.product')),
            ],
        ),
    ]
