# Generated by Django 5.0 on 2024-01-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='data',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
