# Generated by Django 5.0 on 2024-01-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_order_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='data',
            field=models.JSONField(default={'name': 'None'}),
        ),
    ]
