# Generated by Django 5.0 on 2024-01-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='data',
            field=models.JSONField(),
        ),
    ]
